ServerEvents.recipes(event => {
    remove_recipes_id(event, [
        //删除TiC青铜配方
        //"tconstruct:tools/materials/melting/bronze",
        //"tconstruct:smeltery/alloys/molten_bronze",
        ///tconstruct:smeltery\/melting\/metal\/bronze\/(.*)/,
        //删除TiC黄铜配方
        //"tconstruct:tools/materials/melting/plated_slimewood",
        "tconstruct:smeltery/alloys/molten_brass",
        ///tconstruct:smeltery\/melting\/metal\/brass\/(.*)/,
        //删除齿轮,杆，板铸模配方
        /tconstruct:smeltery\/casts\/(.*)\/gear/,
        /tconstruct:smeltery\/casts\/(.*)\/rod/,
        /tconstruct:smeltery\/casts\/(.*)\/plate/,
        //删除TiC安山合金配方
        /tconstruct:compat\/create\/andesite_alloy_(.*)/,
        //删除TiC熔融粘土配方
        "tconstruct:smeltery/casting/clay/block",
        /tconstruct:smeltery\/melting\/clay\/(.*)/,
        /tconstruct:smeltery\/casting\/clay\/brick_(.*)_cast/,
        //移除熔铸炉钢配方
        "tconstruct:smeltery/melting/metal/iron/chain_boots",
        "tconstruct:smeltery/melting/metal/iron/chain_chestplate",
        "tconstruct:smeltery/melting/metal/iron/chain_helmet",
        "tconstruct:smeltery/melting/metal/iron/chain_leggings",
        "tconstruct:smeltery/melting/metal/iron/ore_singular",
        "tconstruct:smeltery/melting/metal/iron/raw",
        "tconstruct:smeltery/melting/metal/iron/raw_block",
        //容器灌注配方
        "tconstruct:smeltery/casting/filling/scorched_ingot_gauge",
        "tconstruct:smeltery/casting/filling/scorched_ingot_tank",
        "tconstruct:smeltery/casting/filling/scorched_fuel_gauge",
        "tconstruct:smeltery/casting/filling/scorched_fuel_tank",
        "tconstruct:smeltery/casting/filling/scorched_lantern_full",
        "tconstruct:smeltery/casting/filling/scorched_lantern_pixel",
        "tconstruct:smeltery/casting/filling/seared_ingot_tank",
        "tconstruct:smeltery/casting/filling/seared_ingot_gauge",
        "tconstruct:smeltery/casting/filling/seared_fuel_gauge",
        "tconstruct:smeltery/casting/filling/seared_fuel_tank",
        "tconstruct:smeltery/casting/filling/seared_lantern_full",
        "tconstruct:smeltery/casting/filling/seared_lantern_pixel",
        //铂、镍
        "tconstruct:smeltery/melting/metal/nickel/raw_block",
        "tconstruct:smeltery/melting/metal/nickel/ore_singular",
        "tconstruct:smeltery/melting/metal/nickel/raw",
        //钨
        "tconstruct:tools/materials/melting/tungsten",
        "tconstruct:smeltery/alloys/molten_tungsten",
        /tconstruct:smeltery\/melting\/metal\/tungsten\/(.*)/,
        //饿
        "tconstruct:tools/materials/melting/osmium",
        "tconstruct:smeltery/alloys/molten_osmium",
        /tconstruct:smeltery\/melting\/metal\/osmium\/(.*)/,
        //琥珀金合金配方
        "tconstruct:smeltery/alloys/molten_electrum",
        //玫瑰金合金配方
        "tconstruct:smeltery/alloys/molten_rose_gold",
        //殷钢合金配方
        "tconstruct:smeltery/alloys/molten_invar",
        //铁粒
        "tconstruct:smeltery/melting/metal/iron/nugget"        
    ])
})